name: Makrut-env
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openh264=2.1.1
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.1.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.4
  - pytorch-mutex=1.0
  - readline=8.1.2
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022a
  - urllib3=1.26.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - aiosignal==1.3.1
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.0.8
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blinker==1.7.0
    - braceexpand==0.1.7
    - brotli==1.1.0
    - cachetools==5.3.0
    - captum==0.6.0
    - chardet==4.0.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - colorama==0.4.6
    - comm==0.1.2
    - contourpy==1.0.6
    - cycler==0.11.0
    - debugpy==1.6.4
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - entrypoints==0.4
    - exceptiongroup==1.1.2
    - executing==1.0.0
    - fastjsonschema==2.16.2
    - filelock==3.12.2
    - flask==3.0.0
    - flask-compress==1.14
    - flatbuffers==24.3.25
    - fonttools==4.37.1
    - fqdn==1.5.1
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - functorch==1.13.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.17.0
    - google-auth-oauthlib==0.4.6
    - gputil==1.4.0
    - grpcio==1.51.3
    - h5py==3.10.0
    - huggingface-hub==0.23.5
    - icecream==2.1.3
    - idna==2.10
    - imageio==2.22.4
    - iniconfig==2.0.0
    - ipdb==0.13.9
    - ipykernel==6.19.2
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.3
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==7.4.8
    - jupyter-console==6.4.4
    - jupyter-core==5.1.0
    - jupyter-events==0.5.0
    - jupyter-server==2.0.1
    - jupyter-server-terminals==0.4.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.4
    - kaggle==1.5.12
    - kaleido==0.2.1
    - kiwisolver==1.4.4
    - kornia==0.6.11
    - libclang==18.1.1
    - lightning-utilities==0.11.2
    - llvmlite==0.41.0
    - markdown==3.4.3
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - msgpack==1.0.5
    - namex==0.0.8
    - nbclassic==0.4.8
    - nbclient==0.7.2
    - nbconvert==7.2.6
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.8.8
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numba==0.58.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - opacus==1.3.0
    - opencv-python==4.9.0.80
    - opt-einsum==3.3.0
    - p2j==1.3.2
    - packaging==21.3
    - pandas==1.5.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pixelmatch==0.3.0
    - platformdirs==2.6.0
    - plotly==5.10.0
    - pluggy==1.2.0
    - progress==1.6
    - prometheus-client==0.15.0
    - promise==2.3
    - prompt-toolkit==3.0.30
    - protobuf==3.20.1
    - psutil==5.9.1
    - ptflops==0.6.9
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==12.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycat==0.1.1
    - pydoe2==1.3.0
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - pytest==7.4.0
    - python-dateutil==2.8.2
    - python-json-logger==2.0.4
    - python-slugify==7.0.0
    - pytorch-msssim==0.2.1
    - pytorchcv==0.0.67
    - pytz==2022.6
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - ray==2.5.1
    - rbo==0.1.3
    - requests==2.25.1
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - safetensors==0.4.3
    - scikit-image==0.19.3
    - scikit-learn==1.2.0
    - scipy==1.9.3
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sentry-sdk==1.9.5
    - setproctitle==1.3.2
    - shap==0.42.1
    - shortuuid==1.0.9
    - sklearn==0.0.post1
    - slicer==0.0.7
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.5.0
    - tabulate==0.9.0
    - tenacity==8.0.1
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==2.4.0
    - terminado==0.17.1
    - text-unidecode==1.3
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - timm==1.0.7
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - torch==1.13.0
    - torchattacks==3.5.1
    - torcheval==0.0.7
    - torchmetrics==1.3.2
    - torchvision==0.14.0
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.7.0
    - typing-extensions==4.12.2
    - ujson==5.6.0
    - uri-template==1.2.0
    - wandb==0.14.0
    - wcwidth==0.2.5
    - webcolors==1.12
    - webdataset==0.2.33
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==3.0.1
    - widgetsnbextension==4.0.4
    - wrapt==1.16.0
